version: '3.8'

services:
  service-a:
    build: ./service-a
    ports:
      - "8080:8080"

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"

  service-c:
    build: ./service-c
    ports:
      - "8082:8082"

  service-d:
    build: ./service-d
    ports:
      - "8083:8083"
